### ISSUE TITLE
Moodle Operator error

### ISSUE THREAD

**Issue by devdattakulkarni** [cloud-ark/kubeplus-operators#66]
MoodleController.go  : Moodle Service IP:10.76.4.13MoodleController.go  : Service URI10.76.4.13:32000
MoodleController.go  : Creating Ingress...
E0824 03:42:57.018419       1 runtime.go:69] Observed a panic: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, Status:"Failure", Message:"Ingress.extensions \"moodle1\" is invalid: spec.tls[0].hosts: Invalid value: \"\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')", Reason:"Invalid", Details:(*v1.StatusDetails)(0xc4205f0de0), Code:422}} (Ingress.extensions "moodle1" is invalid: spec.tls[0].hosts: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'))
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:505
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodle.go:174
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodle.go:33
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:333
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:266
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:276
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:175
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:161
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: Ingress.extensions "moodle1" is invalid: spec.tls[0].hosts: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') [recovered]
	panic: Ingress.extensions "moodle1" is invalid: spec.tls[0].hosts: Invalid value: "": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

goroutine 85 [running]:
github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1104d00, 0xc4204bef30)
	/usr/local/go/src/runtime/panic.go:505 +0x229
main.(*MoodleController).createIngress(0xc420103e60, 0xc4202c2200)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodle.go:174 +0x93d
main.(*MoodleController).deployMoodle(0xc420103e60, 0xc4202c2200, 0xc420070c28, 0x1, 0x1, 0x2f, 0x0, 0x0, 0xc420550f00, 0xc420628600, ...)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodle.go:33 +0x102
main.(*MoodleController).syncHandler(0xc420103e60, 0xc4205d1ac0, 0x12, 0x107b340, 0xc42070e590)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:333 +0x526
main.(*MoodleController).processNextWorkItem.func1(0xc420103e60, 0x107b340, 0xc42070e590, 0x0, 0x0)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:266 +0xda
main.(*MoodleController).processNextWorkItem(0xc420103e60, 0xc42040e3f0)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:276 +0x4f
main.(*MoodleController).runWorker(0xc420103e60)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:175 +0x2b
main.(*MoodleController).(main.runWorker)-fm()
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:161 +0x2a
github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207be580)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4207be580, 0x3b9aca00, 0x0, 0x1, 0xc42044c300)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207be580, 0x3b9aca00, 0xc42044c300)
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by main.(*MoodleController).Run
	/Users/devdatta/go/src/github.com/cloud-ark/kubeplus-operators/moodle/moodlecontroller.go:161 +0x1fb

**Comment by devdattakulkarni** [comment]
This error came with following version of Moodle Operator:
https://github.com/cloud-ark/operatorcharts/blob/master/moodle-operator-chart-0.4.7.tgz
